/**
 * The `/ship` prompt: a canned workflow that takes a one-sentence requirement
 * from idea to shipped, verified code — pre-flight branch isolation, a grill-me
 * interview (design tree, frontier rounds), automatic to-spec (gate 1),
 * automatic to-tickets (gate 2), autonomous TDD landing with anti-cheating
 * proof logging, cascading re-verification, 3-strike circuit breaker, and
 * dual-layer DoD verification.
 *
 * The spec FILE is the workflow's memory, not the conversation: the approved
 * tickets are written into it, its Status line names the phase, its checkboxes
 * are the progress, and a bare /ship offers to resume whatever it finds
 * unfinished. Conversations get interrupted, compacted, and cleared; the file
 * survives all three, which is what makes the landing reliable rather than
 * merely well-intentioned.
 */

/** The `/ship` prompt body; `$ARGUMENTS` is the typed one-sentence requirement. */
export const SHIP_PROMPT = `Run the /ship workflow: take the one-sentence requirement below from idea to shipped, verified code in this repository. The requirement, exactly as typed:

<idea>
$ARGUMENTS
</idea>

If the idea between the <idea> tags is empty, that is not an error. First look for unfinished work: scan the repository's spec directory (docs/specs/, or the repo's own design-document convention) for a spec whose Status line is not \`shipped\` — a bare /ship most likely means "carry on", so offer through ask_user_question to resume that spec from the phase its Status names, with everything below applying from that phase onward. When resuming a spec in landing phase, first enforce cascading re-verification: re-run the proof commands of every checked \`[x]\` ticket in order before starting uncompleted work. If any command fails, degrade that ticket and all subsequent tickets to \`[ ]\` on disk, make the first broken ticket the active ticket, and use the failure logs to repair it in-place. Only when there is nothing to resume, ask for the one-sentence requirement with ask_user_question and use the answer as the idea. Images accompanying the command — [Image #N] tokens, <pasted-image> context, attached image blocks — are part of the requirement: a mockup or a screenshot is requirements material, so read it and cite what it shows in the interview.

Phase 0 — pre-flight & branch isolation. Before modifying any files or cutting tickets, verify git hygiene and isolate the feature. Execute \`git status --porcelain\`. If uncommitted or untracked changes exist in the working tree, do not proceed silently: present an ask_user_question call with \`header\` exactly \`ship · preflight\` and options:
1. Stash (recommended, first): Save uncommitted changes via \`git stash save "ship-preflight-<timestamp>"\` to be restored after delivery.
2. Carry over: Retain existing uncommitted changes in the working tree.
3. Abort: Stop /ship immediately so the user can inspect their workspace.
Once the working tree is clean or settled, record the current commit as \`Base-Commit:\` and current branch as \`Original-Branch:\`. Then derive a concise kebab-case slug for the requirement and create a dedicated feature branch via \`git checkout -b ship/<slug>\`. All implementation, tests, and commits must take place exclusively on this feature branch, so the original branch remains untouched until final delivery.

Phase 1 — grill-me. Research before you ask: read the repository layout, CONTEXT.md if it exists, the docs, ADRs, and the code paths the idea touches. Finding facts is your job, never the user's — where code lives or how current behavior works is yours to find out; do not ask anything inspection can answer. Then map the idea as a design tree: every decision branches into the decisions that hang off it. Work the tree in rounds. The frontier is every decision whose prerequisites are already settled — the questions you can ask now without guessing at answers you have not heard yet. Each round, put the whole frontier into a single ask_user_question call (the tool accepts a list of questions; do not serialize independent frontier questions across separate calls). For each question: a short title, a body grounded in what you found, concrete options rather than an open prompt, and your recommended answer as the first option with a description that says so. Then wait for that call to return before the next round. A question whose answer depends on another still open in this round belongs to a later round. Each round of answers reshapes the tree — settled decisions push the frontier outward. The session is done when the frontier is empty: every branch visited, nothing left silently assumed. Confirm shared understanding through ask_user_question before writing the spec. Do not pad the interview to look thorough, and do not act on the design until that confirmation.

Phase 2 — automatic to-spec (gate 1). Do not interview further — synthesize what the grill already settled and what the codebase already is. Write the spec to a file inside the repository. Follow the repo's existing convention for design documents if one exists (a specs, rfcs, or ADR directory); otherwise create docs/specs/<kebab-case-slug>.md. Use the project's domain glossary throughout, and respect ADRs in the area you are touching. The spec must stand alone for a reader without this conversation, with these sections in order:
- A metadata header with \`Status:\` line (interviewing, confirmed, planned, landing, shipped) kept current at every phase change, followed by \`Branch: ship/<slug>\`, \`Base-Commit:\`, and \`Original-Branch:\`;
- The one-sentence requirement;
- Problem Statement (from the user's perspective);
- Solution (from the user's perspective);
- Each grill decision with its reason;
- User Stories (numbered, "As an <actor>, I want a <feature>, so that <benefit>", covering the feature);
- Implementation Decisions (modules, interfaces, architecture, contracts — no file paths or code snippets unless a prototype encoded a decision more precisely than prose);
- Testing Decisions (what a good test is here: external behavior at public seams, not internals; the seams this spec will be tested at, preferring existing ones; prior art in the repo);
- Out of Scope;
- A numbered list of acceptance criteria where every criterion names the exact command that proves it and the output that counts as passing — the final phase runs those commands verbatim, so a criterion without a command is not finished.
Record the proposed seams in Testing Decisions; the fewer across the codebase, the better — the ideal number is one. Present the spec file path and a compact summary through ask_user_question with \`header\` exactly \`ship · gate 1/2\`, options labeled Confirm (recommended, first), Edit, Abort, and \`detail\` holding that compact summary for the gate modal body — the full summary, one point per line with a blank line between sections (the file path, each section's gist, the acceptance criteria, the testing seams), never a single paragraph: the modal shows the detail line by line and the person approves what they can read. Confirm advances; Edit means revise the spec and ask again; Abort stops /ship. Do not proceed on silence or a vague reply.

Phase 3 — automatic to-tickets (gate 2). Only after the spec is confirmed, and without another interview, break the spec into tracer-bullet tickets: each a narrow but complete vertical slice through every layer it needs (not a horizontal slice of one layer), demoable or verifiable on its own, sized to fit a single fresh context window. Give each ticket its blocking edges — the other tickets that must complete before it can start. Prefactoring that makes the change easy comes first. A wide refactor (one mechanical change whose blast radius fans across the codebase) is the exception: sequence it expand–contract, not as a fake tracer bullet. Always include a final ticket for repository compliance: \`Ticket N: Release & Documentation Compliance — Delivers Changeset and bilingual documentation updates (README.md and README.zh.md) if user-facing code or bundle/cli is touched\`.
Present the breakdown through ask_user_question with \`header\` exactly \`ship · gate 2/2\`, options labeled Confirm (recommended, first), Edit, Abort, and \`detail\` the numbered ticket list — one ticket per line with its title, what it delivers, and what blocks it — plus a baseline note, for the gate modal body; the whole list, never a summary of it. Confirm advances; Edit means revise the tickets and ask again; Abort stops /ship. Fold Edit answers back in and present again. Once approved, write the tickets into the spec file as a \`## Plan\` section with one checkbox per ticket — an approved plan lives on disk, not in a conversation that can be compacted or lost. Each checkbox names the ticket with a concise title, followed by what it delivers and which tickets block it (e.g. \`- [ ] Ticket 1: Short Title — Delivers ... (Blocked by: ...)\`).
Then, still before any implementation code, establish the ground: verify the working tree is clean on the feature branch, and run both the spec's proof commands and the repository's global guardrails (\`pnpm run typecheck\`, test suite) once, recording the baseline in the spec under a \`## Baseline\` section. A baseline that is already red changes what "green" will mean, so surface existing errors here to enable zero-new-failures diff checking rather than discovering them under your own diff. Write no implementation code before this gate passes, and do not use todo_write before it either — it tracks landing, not the grill.

Phase 4 — automatic landing. After gate 2, work autonomously; return to the user only for a genuine blocker that contradicts the spec, never for routine decisions. Either way the spec file — not this conversation — is the working memory: re-read it before starting each ticket, tick the ticket's checkbox and update Status as you go, and commit after each ticket turns green — small commits are the progress that survives a crash and the history a reviewer can walk.
Enforce anti-cheating TDD proof logging at recorded seams: red before green. For each ticket:
1. Red proof: Write or locate the focused test. Run it and capture the actual failure logs with a non-zero exit code, recording that failure proof in the spec or ticket verification log before touching implementation code.
2. Green proof: Implement minimal logic at the declared public seams until the test passes with exit code 0.
3. Clean commits: Produce exactly one clean commit per ticket once all its tests pass. Never commit broken, failing code to git history.
Run typecheck and the focused tests each cycle; run the full suite the spec named once at the end of the ticket. Choose the mechanism by the approved plan's size. If it has at most three tickets and you expect the whole change to fit comfortably in this session's context, implement in-session: track landing with todo_write (recording sub-steps of the active ticket rather than duplicating the plan's ticket titles). If it is larger — four or more substantially independent tickets, or work you expect to exceed what one session can hold — the user running /ship is their explicit request for a fresh-agent Ralph loop: call the ralph tool once, with an objective that names the spec file path as the single source of truth, instructs each round to read the spec from disk (plan, checkboxes, baseline, seams), pick the first unchecked ticket whose blockers are ticked, implement it test-first at those seams, then commit and tick its checkbox, and defines completion as every acceptance criterion in the spec passing. Bound the loop: budget about three rounds per ticket, and instruct it to stop and report rather than continue past two consecutive rounds that tick nothing.
Enforce a three repair attempts circuit breaker per ticket: if a ticket cannot turn green after three attempts, halt autonomous thrashing. In a Ralph loop, stop immediately and emit a structured Blocker report. In the main session, use ask_user_question to surface the failure diagnosis and request human guidance.

Phase 5 — done means verified. The workflow ends only when dual-layer DoD passes. Layer 1: Every acceptance criterion passes with you actually running its named command and reading the real output (exit code 0 required). Layer 2: Global repository guardrails (typecheck, tests, and changeset checks) pass with zero new failures against the Phase 3 baseline. After a Ralph loop returns, run every proof command again yourself — the loop's word is a report, not a verification. Never report a result you did not run, and never weaken a criterion to make it pass; if one cannot be met, say so plainly and why. When a decision changes mid-flight, update the spec file first so the file on disk stays the truth.
Set Status to shipped only after that final run. Then present the post-ship delivery modal through ask_user_question with \`header\` exactly \`ship · deliver\` and three options:
1. Merge back (recommended, first): Merge the feature branch into the original branch via fast-forward or squash merge, and delete the feature branch.
2. Keep branch for PR: Leave the feature branch intact and print the command to push to remote (\`git push -u origin ship/<slug>\`).
3. Stay on branch: Remain on \`ship/<slug>\` for manual inspection in the working tree.
Close with an honest report listing each criterion, the command that proved it, what it printed, and the delivery action selected.

If the session is in plan mode, the plan-mode rules win: nothing here authorizes writes while it is active. Tell the user this workflow needs to write the spec file and ask them to leave plan mode before continuing past the interview.`
