/**
 * The `/ship` prompt: a canned workflow that takes a one-sentence requirement
 * from idea to shipped, verified code — pre-flight branch isolation, grill-me
 * as the grill-me skill (design tree, frontier rounds), automatic to-spec
 * (gate 1) as the to-spec skill, automatic to-tickets (gate 2) as the
 * to-tickets skill, autonomous landing as the tdd skill with anti-cheating
 * proof logging, cascading re-verification, 3-strike circuit breaker, and
 * dual-layer DoD verification.
 *
 * The spec FILE is the workflow's memory, not the conversation: the approved
 * tickets are written into it, its Status line names the phase, its checkboxes
 * are the progress, and a bare /ship offers to resume whatever it finds
 * unfinished. Conversations get interrupted, compacted, and cleared; the file
 * survives all three, which is what makes the landing reliable rather than
 * merely well-intentioned.
 */

/** The `/ship` prompt body; `$ARGUMENTS` is the typed one-sentence requirement. */
export const SHIP_PROMPT = `Run the /ship workflow: take the one-sentence requirement below from idea to shipped, verified code in this repository. The requirement, exactly as typed:

<idea>
$ARGUMENTS
</idea>

If the idea between the <idea> tags is empty, that is not an error. First look for unfinished work: scan the repository's spec directory (docs/specs/, or the repo's own design-document convention) for a spec whose Status line is not \`shipped\` — a bare /ship most likely means "carry on", so offer through ask_user_question to resume that spec from the phase its Status names, with everything below applying from that phase onward. When resuming a spec in landing phase, first enforce cascading re-verification: re-run the proof commands of every checked \`[x]\` ticket in order before starting uncompleted work. If any command fails, degrade that ticket and all subsequent tickets to \`[ ]\` on disk, make the first broken ticket the active ticket, and use the failure logs to repair it in-place. Only when there is nothing to resume, ask for the one-sentence requirement with ask_user_question and use the answer as the idea. Images accompanying the command — [Image #N] tokens, <pasted-image> context, attached image blocks — are part of the requirement: a mockup or a screenshot is requirements material, so read it and cite what it shows in the interview.

Phase 0 — pre-flight & branch isolation. Before modifying any files or cutting tickets, verify git hygiene and isolate the feature. Execute \`git status --porcelain\`. If uncommitted or untracked changes exist in the working tree, do not proceed silently: present an ask_user_question call with \`header\` exactly \`ship · preflight\` and options:
1. Stash (recommended, first): Save uncommitted changes via \`git stash save "ship-preflight-<timestamp>"\` to be restored after delivery.
2. Carry over: Retain existing uncommitted changes in the working tree.
3. Abort: Stop /ship immediately so the user can inspect their workspace.
Once the working tree is clean or settled, record the current commit as \`Base-Commit:\` and current branch as \`Original-Branch:\`. Then derive a concise kebab-case slug for the requirement and create a dedicated feature branch via \`git checkout -b ship/<slug>\`. All implementation, tests, and commits must take place exclusively on this feature branch, so the original branch remains untouched until final delivery.

Phase 1 — grill-me. Follow the grill-me skill as the contract, not a summary of it. Core invariants that may not be dropped: Relentless Frontier Exploration — model the design space as a decision tree and exhaust the frontier before declaring alignment. One Question Round per Turn — batch the entire unblocked frontier into structured rounds with recommended defaults; never interrogate with one-off dribble. Autonomous Fact Extraction — retrieve codebase, system, and file facts yourself; never ask the user what inspection can reveal. Active Assumption Invalidation — proactively challenge comfortable assumptions, scale bottlenecks, edge-case failure modes, security boundaries, migration paths, and hidden dependencies. No Premature Implementation — refuse to write production code or tickets until the interview frontier is completely empty and mutually agreed. Mandatory grilling: the one-sentence idea is never clear enough to skip this phase.
Research before you ask: read the repository layout, CONTEXT.md if it exists, the docs, ADRs, and the code paths the idea touches. Finding facts is your job, never the user's — where code lives or how current behavior works is yours to find out; do not ask anything inspection can answer. Then map the idea as a design tree: every decision branches into the decisions that hang off it. Work the tree in rounds under Strict Topological Dependency Ordering: the frontier is every decision whose prerequisites are already settled — the questions you can ask now without guessing at answers you have not heard yet. A question whose answer depends on another still open in this round belongs to a later round.
Each round, put the whole frontier into a single ask_user_question call with \`header\` exactly \`ship · grill\` (the tool accepts a list of questions; do not serialize independent frontier questions across separate calls — that header is what opens the compact grill card). For each question: a short title, a body grounded in what you found that names a genuine decision rather than an environmental fact, concrete options rather than an open prompt, and your recommended answer as the first option with a description that says so (Mandatory Concrete Recommendations — every question carries a definitive recommended answer). Then wait for that call to return before the next round. If an answer is vague, clarify it immediately; do not guess what they meant. Each round of answers reshapes the tree — settled decisions push the frontier outward. Probe the edges: failure modes, security boundaries, migration paths, and non-happy paths. Do not pad the interview to look thorough, and do not agree with a preferred approach without challenging its trade-offs.
The session is done only at the Verified Exhaustion Gate: the frontier is empty (every branch visited, nothing left silently assumed) and the user explicitly validates the final consensus. Present a concise synthesis of the unified decision contract through ask_user_question with \`header\` exactly \`ship · grill\` and confirm shared understanding before writing the spec. Do not act on the design until that confirmation.

Phase 2 — automatic to-spec (gate 1). Follow the to-spec skill as the contract, not a summary of it. Core invariants that may not be dropped: Pure Synthesis, Zero Interrogation — Do not interview further; synthesize strictly from what the grill already settled and what the codebase already is. Exhaustive User Stories. Minimal Seams at the Highest Tier. Decisions Over Concrete Snippets. Strict Out-of-Scope Demarcation. First inspect the repository: modules, domain glossary, ADRs, and the highest available integration seam for external verification. Write the spec to a file inside the repository. Follow the repo's existing convention for design documents if one exists (a specs, rfcs, or ADR directory); otherwise create docs/specs/<kebab-case-slug>.md. Also keep a working copy at \`.scratch/<kebab-case-slug>/spec.md\` so a later to-tickets pass has a local store even when the issue tracker is unconfigured. The spec must stand alone for a reader without this conversation, with these sections in order:
- A metadata header with \`Status:\` line (interviewing, confirmed, planned, landing, shipped) kept current at every phase change, followed by \`Branch: ship/<slug>\`, \`Base-Commit:\`, and \`Original-Branch:\`;
- The one-sentence requirement;
- Problem Statement (from the user's perspective);
- Solution (from the user's perspective);
- Each grill decision with its reason;
- User Stories — exhaustive, numbered, each exactly \`1. As an <actor>, I want a <feature>, so that <benefit>\`. Edge cases and failure states are covered as distinct stories. Every story has an explicit actor and a tangible benefit. No implementation jargon inside the stories;
- Implementation Decisions (module boundaries, interfaces, architecture, schema and API contracts — no file paths, line numbers, or speculative code snippets unless a validated prototype encoded a decision more precisely than prose);
- Testing Decisions (behavior at public seams, never internals or mock-heavy private helpers; the highest available existing seam, preferring one seam across the codebase; prior art in the repo);
- Out of Scope — mandatory explicit negative boundaries, even when they seem obvious;
- A numbered list of acceptance criteria where every criterion names the exact command that proves it and the output that counts as passing — the final phase runs those commands verbatim, so a criterion without a command is not finished.
Record the proposed seams in Testing Decisions; the fewer across the codebase, the better — the ideal number is one. Publish: if the repository already has an issue tracker configured for agent work, create or update the parent spec issue there and apply the \`ready-for-agent\` triage label. If the tracker is unconfigured, keep \`.scratch/<kebab-case-slug>/spec.md\` as the local store and tell the user to run \`/setup-engineering-workflows\` so later tickets can land in the tracker; do not invent a tracker. Present the spec file path and a compact summary through ask_user_question with \`header\` exactly \`ship · gate 1/2\`, options labeled Confirm (recommended, first), Edit, Abort, and \`detail\` holding that compact summary for the gate modal body — the full summary, one point per line with a blank line between sections (the file path, each section's gist, the acceptance criteria, the testing seams), never a single paragraph: the modal shows the detail line by line and the person approves what they can read. Confirm advances; Edit means revise the spec and ask again; Abort stops /ship. Do not proceed on silence or a vague reply.

Phase 3 — automatic to-tickets (gate 2). Only after the spec is confirmed, and without another interview, follow the to-tickets skill as the contract. Core invariants that may not be dropped: Strict Vertical Tracer Slicing — every standard ticket cuts vertically across every layer it needs (schema, domain, API, UI, test), never a horizontal slice of one layer. Explicit Dependency DAG — every ticket declares \`Blocked by:\`. Single Context-Window Sizing. Expand-Contract for Wide Refactors. No Parent Mutation — Never close, resolve, or corrupt parent tracker issues when authoring child tickets. Inspect the codebase for prefactoring first: if the existing code makes the change hard, Ticket 1 is that preparatory refactor and nothing else. Then break the spec into tracer-bullet tickets: each independently verifiable, sized to fit a single fresh context window. A wide refactor is sequenced expand–contract (expand → batch migrate → contract), not as a fake tracer bullet. Every ticket carries an atomic acceptance checklist — binary, testable, self-contained, so an implementer does not have to re-read the spec to know done. Always include a final ticket for repository compliance: \`Ticket N: Release & Documentation Compliance — Delivers Changeset and bilingual documentation updates (README.md and README.zh.md) if user-facing code or bundle/cli is touched\`.
Present the breakdown through ask_user_question with \`header\` exactly \`ship · gate 2/2\`, options labeled Confirm (recommended, first), Edit, Abort, and \`detail\` the numbered ticket list — one ticket per line with its title, what it delivers, its atomic acceptance checklist in brief, and what blocks it — plus a baseline note, for the gate modal body; the whole list, never a summary of it. Confirm advances; Edit means revise the tickets and ask again; Abort stops /ship. Fold Edit answers back in and present again. Once approved, write the tickets in two places, blockers first (topological order so downstream tickets can name live upstream ids): (1) the spec file as a \`## Plan\` section with one checkbox per ticket — an approved plan lives on disk, not in a conversation that can be compacted or lost — each checkbox names the ticket with a concise title, followed by what it delivers and which tickets block it (e.g. \`- [ ] Ticket 1: Short Title — Delivers ... (Blocked by: ...)\`); (2) one Markdown file per ticket at \`.scratch/<kebab-case-slug>/issues/NN-<slug>.md\` carrying title, blockers, deliverable, and the atomic acceptance checklist. If the issue tracker is configured, also publish those tickets there in the same topological order, apply \`ready-for-agent\` to every unblocked ticket, and never mutate the parent spec issue. If the tracker is unconfigured, the \`.scratch/\` files are the store; remind the user to run \`/setup-engineering-workflows\`.
Then, still before any implementation code, establish the ground: verify the working tree is clean on the feature branch, and run both the spec's proof commands and the repository's global guardrails (\`pnpm run typecheck\`, test suite) once, recording the baseline in the spec under a \`## Baseline\` section. A baseline that is already red changes what "green" will mean, so surface existing errors here to enable zero-new-failures diff checking rather than discovering them under your own diff. Write no implementation code before this gate passes, and do not use todo_write before it either — it tracks landing, not the grill.

Phase 4 — automatic landing. After gate 2, work autonomously; return to the user only for a genuine blocker that contradicts the spec, never for routine decisions. Either way the spec file — not this conversation — is the working memory: re-read it before starting each ticket, tick the ticket's checkbox and update Status as you go, and commit after each ticket turns green — small commits are the progress that survives a crash and the history a reviewer can walk.
Landing follows the tdd skill as the contract. Core invariants that may not be dropped: Strict Red-First Execution — never write production implementation before seeing an automated test fail against the pre-agreed public seam. Behavioral Testing Over Implementation Inspection — assert observable input/output and public contracts, never private variables or internal call chains. Independent Expected Values — compare against fixtures, domain specs, or known literals, never recomputed mirror logic. Vertical Tracer Slicing — one test → minimal code → green, not a batch of tests written before any code. Deterministic & Isolated Fixtures — milliseconds, no leaked state, unseeded random, or unpinned clocks. For each ticket, and for each vertical slice inside it:
1. Identify the public seam the spec named. State the observable contract.
2. Red: write one focused failing test that names the business capability. Run it and witness it fail for the right reason — the new behavior is absent, not a syntax or setup error — and record that non-zero exit code and the failure log in the spec or ticket verification log before touching implementation code. A test that passes on the first run without a code change is tautological or wrong: investigate, do not proceed.
3. Green: write only the minimal code that makes that one test pass. No speculative branches, no unexercised paths.
4. Verify: run the full test suite and typecheck; all must be green before the next slice. Then the next test, not a pile of tests.
Anti-cheating TDD proof logging still applies: red before green, and you actually ran the command. Once every slice on the ticket is green, produce exactly one clean commit per ticket. Never commit broken, failing code to git history. Run the full suite the spec named once at the end of the ticket.
Choose the mechanism by the approved plan's size. If it has at most three tickets and you expect the whole change to fit comfortably in this session's context, implement in-session: track landing with todo_write (recording sub-steps of the active ticket rather than duplicating the plan's ticket titles). If it is larger — four or more substantially independent tickets, or work you expect to exceed what one session can hold — the user running /ship is their explicit request for a fresh-agent Ralph loop: call the ralph tool once, with an objective that names the spec file path as the single source of truth, instructs each round to read the spec from disk (plan, checkboxes, baseline, seams), pick the first unchecked ticket whose blockers are ticked, implement it through the tdd skill at those seams (red witnessed, then minimal green, then the suite), then commit and tick its checkbox, and defines completion as every acceptance criterion in the spec passing. Bound the loop: budget about three rounds per ticket, and instruct it to stop and report rather than continue past two consecutive rounds that tick nothing.
Enforce a three repair attempts circuit breaker per ticket: if a ticket cannot turn green after three attempts, halt autonomous thrashing. In a Ralph loop, stop immediately and emit a structured Blocker report. In the main session, use ask_user_question to surface the failure diagnosis and request human guidance.

Phase 5 — done means verified. The workflow ends only when dual-layer DoD passes. Layer 1: Every acceptance criterion passes with you actually running its named command and reading the real output (exit code 0 required). Layer 2: Global repository guardrails (typecheck, tests, and changeset checks) pass with zero new failures against the Phase 3 baseline. After a Ralph loop returns, run every proof command again yourself — the loop's word is a report, not a verification. Never report a result you did not run, and never weaken a criterion to make it pass; if one cannot be met, say so plainly and why. When a decision changes mid-flight, update the spec file first so the file on disk stays the truth.
Set Status to shipped only after that final run. Then present the post-ship delivery modal through ask_user_question with \`header\` exactly \`ship · deliver\` and three options:
1. Merge back (recommended, first): Merge the feature branch into the original branch via fast-forward or squash merge, and delete the feature branch.
2. Keep branch for PR: Leave the feature branch intact and print the command to push to remote (\`git push -u origin ship/<slug>\`).
3. Stay on branch: Remain on \`ship/<slug>\` for manual inspection in the working tree.
Close with an honest report listing each criterion, the command that proved it, what it printed, and the delivery action selected.

If the session is in plan mode, the plan-mode rules win: nothing here authorizes writes while it is active. Tell the user this workflow needs to write the spec file and ask them to leave plan mode before continuing past the interview.`
