# codsh --rust fish completion. Source this file; it does not start a session.
complete -c codsh -n '__fish_use_subcommand' -a 'help' -d 'Print help'
complete -c codsh -n '__fish_use_subcommand' -a 'completions' -d 'Generate a shell completion script'
complete -c codsh -n '__fish_use_subcommand' -a 'inspect' -d 'Show discovered configuration'
complete -c codsh -n '__fish_use_subcommand' -a 'import' -d 'Preview or apply imported settings'
complete -c codsh -n '__fish_use_subcommand' -a 'feedback' -d 'Send feedback'
complete -c codsh -n '__fish_use_subcommand' -a 'plugin' -d 'Manage plugins'
complete -c codsh -n '__fish_use_subcommand' -a 'login' -d 'Sign in'
complete -c codsh -n '__fish_use_subcommand' -a 'logout' -d 'Sign out'
complete -c codsh -n '__fish_use_subcommand' -a 'setup' -d 'Fetch managed configuration'
complete -c codsh -n '__fish_use_subcommand' -a 'voice' -d 'List microphones'
complete -c codsh -n '__fish_use_subcommand' -a 'sessions' -d 'List or search sessions'
complete -c codsh -n '__fish_use_subcommand' -a 'dashboard' -d 'Open the agent dashboard'
complete -c codsh -n '__fish_use_subcommand' -a 'web' -d 'Call the configured web substitutes'
complete -c codsh -n '__fish_use_subcommand' -a 'export' -d 'Export a session as Markdown'
complete -c codsh -n '__fish_use_subcommand' -a 'share' -d 'Share a session with the configured service'
complete -c codsh -n '__fish_use_subcommand' -a 'du disk-usage' -d 'Show isolated-home disk usage'
complete -c codsh -n '__fish_use_subcommand' -a 'memory' -d 'Manage local memory notes'
complete -c codsh -n '__fish_seen_subcommand_from completions' -a 'bash elvish fish powershell zsh' -d 'Target shell'
complete -c codsh -l help -s h -d 'Print help'
complete -c codsh -l version -s V -d 'Print version'
complete -c codsh -s v -d 'Print version'
complete -c codsh -l continue -s c -d 'Continue the most recent session'
complete -c codsh -l resume -s r -d 'Resume a session by id or title'
complete -c codsh -l fork-session -d 'Copy a resumed session'
complete -c codsh -l session-id -s s -d 'Session id for --fork-session'
complete -c codsh -l model -s m -d 'Model id'
complete -c codsh -l effort -d 'Reasoning effort'
complete -c codsh -l reasoning-effort -d 'Reasoning effort'
complete -c codsh -l cwd -d 'Working directory'
complete -c codsh -s p -l single -d 'Plain prompt'
complete -c codsh -l prompt-file -d 'Plain prompt file'
complete -c codsh -l prompt-json -d 'Plain prompt JSON'
complete -c codsh -l verbatim -d 'Send the prompt as given'
complete -c codsh -l tools -d 'Allow listed tools'
complete -c codsh -l disallowed-tools -d 'Remove listed tools'
complete -c codsh -l max-turns -d 'Maximum agent steps'
complete -c codsh -l rules -d 'Append session rules'
complete -c codsh -l append-system-prompt -d 'Append session rules'
complete -c codsh -l system-prompt-override -d 'Replace the system prompt'
complete -c codsh -l system-prompt -d 'Replace the system prompt'
complete -c codsh -l allow -d 'Permission allow rule'
complete -c codsh -l deny -d 'Permission deny rule'
complete -c codsh -l always-approve -d 'Auto-approve tool executions'
complete -c codsh -l yolo -d 'Auto-approve tool executions'
complete -c codsh -l permission-mode -a 'ask auto always-approve dontAsk acceptEdits' -d 'Permission mode'
complete -c codsh -l output-format -a 'plain json streaming-json streaming-messages-json' -d 'Output format'
complete -c codsh -l trust -d 'Trust this folder'
complete -c codsh -l revoke-trust -d 'Withdraw folder trust'
complete -c codsh -l minimal -d 'Minimal screen'
complete -c codsh -l fullscreen -d 'Fullscreen screen'
complete -c codsh -l sandbox -a 'off workspace read-only strict devbox' -d 'Filesystem sandbox profile'
complete -c codsh -l no-memory -d 'Hide memory for this process'
complete -c codsh -l disable-web-search -d 'Disable web search and web fetch tools'
